{"baseCenterX": [30, 30, 30, 26.75, 53.5, 80.25, 107.0, 133.75, 133.75, 107.0, 80.25, 53.5, 26.75], "baseCenterY": [0, 0, 67.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5], "baseCenterZ": [37.5, 37.5, 37.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "heightVectX": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "heightVectY": [67.5, 30.25, -30.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "heightVectZ": [0, 0, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10], "radius": [17.5, 27.5, 27.5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], "subtraction": [true, true, true, true, true, true, true, true, true, true, true, true, true], "cylinder_func": [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}