{
    
    "box_test" : "I need a box, that is on the upside open. The outer dimensions are 220 x 300 x 160mm. The wall thickness should be 8mm and the bottom thickness 12mm. Add two cylinders on the sides of box, each with thickness of 10 mm and radius of 30 mm",
    "box_test_2" : "I need a box, that is on the upside open. The outer dimensions are 220 x 300 x 160mm. The wall thickness should be 8mm and the bottom thickness 12mm. Add two cylinders on the sides of box, each with thickness of 10 mm and radius of 30 mm. The cylinders and the side of the box must be parallel",
    "box_a" : "I need a box, that is on the upside open. The outer dimensions are 220 x 300 x 160mm. The wall thickness should be 8mm and the bottom thickness 12mm",
    "box_b" : "I want a rectangular box that is 220mm wide, 300mm long and 160mm high. Let it be on the upside open and have walls with 8mm thickness and a 12mm thick bottom.",
    "box_c" : "Create an open top box (220x300x160mm) with wall thickness of 8mm and bottom thickness of 12mm.",
    "toycar_a" : "Let's create the model of a toy car. For the body create a box with size 200x100x100. Subtract a block of size 50x100x50 at an edge for the windshield part. For the Wheels add Four Cylinders, at the bottom of the car which is the XY Plane, with radius 25 and a length of 10mm pointing in the Y-Direction.",
    "toycar_b" : "I want to create a toy car model. Create a box with dimensions 200x100x100 for the body. The windshield can be created by subtracting a 50x100x50 block at an upper edge of the box. Create four wheels at the each bottom edge of the car with cylinders of radius 25 with a height of 10mm in the direction (0,1,0).  Make sure that they touch the box.",
    "toycar_c" : "I want to model a toycar. The body is a box with shape 200x100x100 (X,Y,Z). For the windshield subtract a block of size 50x100x50 on a top edge. The wheels should be placed at the four corners at bottom of the box, which is the XY Plane. Make sure that the wheels are facing in the Y-Axis with a thickness of 10mm and radius 25mm.",
    "u_profile_a" : "Please create a u-shaped profile. The cross section should be 70mm wide and 40mm high. The web thickness needs to be 5mm. The profile should be 450mm long.",
    "u_profile_b" : "Generate a U-shaped profile by subtracting an offset rectangular box from a larger one, ensuring both ends remain open. The larger box should measure 450 mm in length, 70 mm in width, and 40 mm in height. Subtract an inner box that is 60 mm wide and 35 mm and high with same 450mm length, maintain a wall thickness of 5 mm around the sides and base, resulting in a U-shape, open at the top and sides",
    "u_profile_c" : "I need a channel beam with 70mm width, 40mm height, a length 450mm with a wall thickness of 5mm, which is open on the top side",
    "right_angle_a" : "I want an angular plate with two quadratic plates positioned in right angel to each other. The edge length of the plates is 140mm. They are 10mm thick. On one of the two plates I would like to have a quadratic cutout, 45x45mm, centred on the plate.",
    "right_angle_b" : "Design a geometric model consisting of two square plates, each with an edge length of 140mm and a thickness of 10mm. Position these plates so that they intersect at a 90-degree angle, creating an L-shape configuration. On one of these plates, incorporate a square cutout measuring 45x45mm.",
    "right_angle_c" : "Create an corner with two 140x140 plates at a 90° angle to each other. The first plate has in its center a cutout of 45x45. All plates are 10mm thick",
    "FCRC_a" : "The Part is a rectangular block with features. Rectangular Block: 160.5mm length in X-axis direction, 67.5mm width in Y-axis direction, 70mm height in Z-axis direction. Main Counterbore Cylinder: Inner Cylinder: Axis at X=30mm, Z=37.5mm, parallel to Y-axis. Diameter 35mm trough hole part. Two additional Cylinders at same point and also parallel to Y-Axis with diameter 55mm from both surfaces penetrating into part, each such deep that 7mm material is left in centre. A force of 34.155 kN is applied on the inner cylinder, in direction (-0.9962,0,0.0872) Screw Fixation Holes: 10mm diameter. The fist hole is positioned at X=26.75mm, Y=7.5mm, axis in Z-axis direction with 10mm length. Four holes are placed with a distance of 26.75mm in X-axis direction between each hole and the previous one. This pattern with 5 holes is mirrored to the other side of the part on the middle axis of the part in X-axis direction. These holes are the connection to the supporting structure.",
    "FCRC_b": "Overview The FCRC bracket is a rectangular block with dimensions 160.5 x 67.5 x 70 mm, positioned at the origin of the coordinate system. The bracket features a series of cylindrical holes and screw fixation holes, as detailed below. Cylindrical Holes The bracket features three cylindrical holes centered at the same point (30, 37.5) on the XZ plane: • The first hole is a through hole with a radius of 17.5 mm that spans the full length of the block along the Y-axis, from Y = 0 to Y = 67.5 mm. At this hole a force of 34.155 kN is applied in direction (-0.9962,0,0.0872) • The second hole has a radius of 27.5 mm, but it extends only from Y=0 mm to Y=29 mm. • The third hole starts at Y=36mm and goes until the other end of the block at Y=67.5 Screw Fixation Holes  The bracket features ten screw fixation holes, aligned on the bracket's bottom surfaces (XY Plane), maintaining a 7.5mm margin from the bracket's outer edges. • Five holes are placed on each side of the bracket, along the X-Axis, spaced 27.5mm apart from its neighbors and the ends. • All holes have a diameter of 10mm (radius of 5mm) and extend 10mm into the bracket, ensuring robust attachment points for the FCRC bracket. Those holes function as support structure",
    "FCRC_c" : "Overview The FCRC bracket is a rectangular block with dimensions 160.5 x 67.5 x 70 mm, positioned at the origin of the coordinate system. The bracket features a series of cylindrical holes and screw fixation holes, as detailed below. Cylindrical Holes: The bracket features three cylindrical holes centered at the same point (X = 30, Z = 37.5) on the XZ plane: • The first hole is a through hole with a radius of 17.5 mm that spans the full length of the block along the Y-axis, from Y = 0 to Y = 67.5 mm. At this hole a force of 34.155 kN is applied in direction (-0.9962,0,0.0872) • The second hole has a radius of 27.5 mm, but it extends only from Y=0 mm to Y=29 mm. • The third hole starts at Y=36mm and goes until the other end of the block at Y=67.5 /n Screw Fixation Holes: 10mm diameter. The fist hole is positioned at X=26.75mm, Y=7.5mm, axis in Z-axis direction with 10mm length. Four holes are placed with a distance of 26.75mm in X-axis direction between each hole and the previous one. This pattern with 5 holes is mirrored to the other side of the part on the middle axis of the part in X-axis direction. These holes are the connection to the supporting structure.",
    "FCRC_d": "Overview: The FCRC bracket is a rectangular block with dimensions 160.5 x 67.5 x 70 mm, positioned at the origin of the coordinate system. The bracket features a series of cylindrical holes and screw fixation holes, as detailed below. Cylindrical Holes The bracket features three cylindrical holes centered at the same point (30, 37.5) on the XZ plane: • The first hole is a through hole with a radius of 17.5 mm that spans the full length of the block along the Y-axis, from Y = 0 to Y = 67.5 mm. At this hole is the force application boundary with 34.155 kN being applied in direction (-0.9962,0,0.0872) • The second hole has a radius of 27.5 mm, but it extends only from Y=0 mm to Y=29 mm. • The third hole starts at Y=36mm and goes until the other end of the block at Y=67.5 /n Screw Fixation Holes The bracket features 10 screw fixation holes with diameter = 10mm, starting from the bracket's bottom surface (XY Plane), The fist hole is positioned at X=26.75mm, Y=7.5mm Z=0, Height is in 10mm in Z-Axis direction. Four holes are placed with a distance of 26.75mm in X-axis direction between each hole and the previous one. This pattern with 5 holes is mirrored on the XZ Plane with Y=60. These 10 holes are the fixation to the supporting structure.",
    "FCRC_e": "I need a Bracket made up from the following Geometries: A rectangular Block with dimensions (160.5,67.5,70) positioned at the origin (0,0,0). \n First Hole (Through Hole): Location: Centered at (X=30 mm, Z=37.5 mm) on the XZ plane, spanning the entire height of the bracket along the Y-axis (0 to 67.5 mm). Diameter: 35 mm (radius of 17.5 mm).Force Application: A force of 34.155 kN is applied along the vector (-0.9962, 0, 0.0872).\n Second Hole: Location: Centered at (X=30 mm, Z=37.5 mm) on the XZ plane. Diameter: 55 mm (radius of 27.5 mm). Extent: Extends from the XZ surface (Y=0 mm) to Y=29 mm.\n Third Hole: Location: Centered at (X=30 mm, Z=37.5 mm) on the XZ plane. Diameter: 55 mm (radius of 27.5 mm). Extent: Begins at Y=36 mm and extends to the other XZ surface of the bracket with Y=67.5 mm.\n Screw Fixation Holes: Details: Each hole has a diameter of 10 mm and extends 10 mm in Z-Direction from the starting Z-coordinate (Z=0). First Row: Starting Position: The first hole is located at (X=26.75 mm, Y=7.5 mm, Z=0). Pattern: Four additional holes are spaced 26.75 mm apart along the X-axis, all at Y=7.5 mm. Second Row (Mirrored on the XZ Plane): Y-Position: At Y=60 mm, mirroring the first row along the X-axis.",
    "simple_bracket_a" : "Create a Box with Dimensions 70x80x90. On the top are four holes, each with a diameter of 10mm and a depth of 10mm. The holes are positioned in a square with a distance of 20mm from each other and distanced 5mm the Edges in the top left corner. An additional set of holes is placed on the right side of the box. It's also 4 holes with diameter of 10mm in the bottom right corner 5mm from the edges. The holes are also in a square with a distance of 20mm from each other. The first holes are subject to a force of 20kN in direction (0.75,0,0.6) and the second set of holes are the fixture",
    "simple_bracket_b" : "Create a box with dimensions 70x80x90. There is a hole at 30,30,0 with diameter 15 and depth 10 in Positive Z-axis. It is subject to a force of 20kN in direction (0.75,0,0.6). There are 2 holes as structural boundary fixture: One hole at 60,0,20 with diameter 12 and depth 10 in Positive Y-Axis and a second hole at 0,20,80 with diameter 12 and depth 10 in Positive X-Axis.",
    "simple_bracket_c" : "I have an outer bounding box with dimensions 30x40x50."
}